name: Build

on: [push, pull_request]

jobs:
  test:
    runs-on: macos-15

    steps:
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: "26"
      - uses: actions/checkout@v2
      - name: Run Test
        run: xcodebuild -scheme swift-concurrency-task-manager test -destination 'platform=iOS Simulator,name=iPhone 17 Pro,OS=26' | xcpretty
