name: Build

on: [push, pull_request]

jobs:
  test:
    runs-on: macos-13

    steps:
      - uses: maxim-lobanov/setup-xcode@v1.1
        with:
          xcode-version: "14.3"
      - uses: actions/checkout@v2
      - name: Run Test
        run: xcodebuild -scheme swift-concurrency-task-manager test -destination 'platform=iOS Simulator,name=iPhone 14 Pro,OS=16.4' | xcpretty
