name: Build

on: [push, pull_request]

jobs:
  test:
    runs-on: macos-14

    steps:
      - uses: maxim-lobanov/setup-xcode@v1.6
        with:
          xcode-version: "16.0"
      - uses: actions/checkout@v2
      - name: Run Test
        run: xcodebuild -scheme swift-concurrency-task-manager test -destination 'platform=iOS Simulator,name=iPhone 15 Pro,OS=18.0' | xcpretty
